# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pass bot token as environment variable
        run: |
          echo "export DISCORD_BOT_TOKEN=${{ secrets.LAYCHPA_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest  # Or any other test command you use
