name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure all dependencies are installed
          pip install pytest  # Explicitly install pytest

      - name: Set bot token
        run: echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> $GITHUB_ENV  # Sets the token as an environment variable

      - name: Run tests
        run: pytest
        shell: /usr/bin/bash -e {0}
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.LAYCHPA_BOT_TOKEN }}  # Passes the token to the test environment
